### ISSUE TITLE
Load order conflicts with The Dance of Death - Ultimate Edition

### ISSUE THREAD

**Issue by tjbassoon** [loot/skyrim#115]
The Dance of Death - Ultimate Edition.esp must load after the following:
ogDiverseDragons.esp
Vigor - Combat and Injuries.esp

If this condition is not met the main menu at the title screen will not appear. I would welcome someone else confirming.

**Comment by Ortham** [comment]
I don't see any mention of this issue anywhere, and looking at the plugin headers there's no inter-dependencies, so I'm guessing this happened because the original Dragons Diversified (`ogDiverseDragons.esp`) is incompatible with Dragonborn rather than anything in The Dance of Death - Ultimate Edition.

Closing this as invalid, if anyone has evidence otherwise, it can be re-opened.
