### ISSUE TITLE
Jaggarsfeld Extended.esp UDR/ITM Cleaning Report

### ISSUE THREAD

**Issue by inire** [loot/skyrim#117]
http://www.nexusmods.com/skyrim/mods/68104/?

LOOT Masterlist Entry
- name: 'Jaggarsfeld Extended.esp'
  dirty:
  - crc: 0x239a664f
    util: *dirtyUtil
    itm: 1
    udr: 178

BOSS Masterlist Entry
Jaggarsfeld Extended.esp
  IF CHECKSUM("Jaggarsfeld Extended.esp", 239A664F) DIRTY: 1 ITM, 178 UDR records. Needs TES5Edit cleaning: "http://cs.elderscrolls.com/index.php?title=TES4Edit_Cleaning_Guide"

**Comment by TechAngel85** [comment]
As the author, I am aware of the ITM and UDRs. You shouldn't clean the UDRs. You'll likely have some issues if you do.
There is little point of adding this to LOOT. Jaggarsfeld Extended will be absorbed into the main mod page in due time and at that time I will be re-working some things so these will not be an issue. For now I'm only supporting Jaggarsfeld Extended in a limited fashion since most of my work is going into the main mod.

**Comment by TechAngel85** [comment]
I've cleaned the ITM from the mod and may or may not work on the UDRs.

**Comment by Ortham** [comment]
@TechAngel85: In all my years of this stuff, I've never come across a single case where UDRs should not be cleaned. ITMs, yes, sometimes they are intentional, but deleting a reference has to my knowledge always been the wrong thing to do.

**Comment by TechAngel85** [comment]
The UDRs are my rookie mistake when I first made the mod. I've played the game for hours and hours without an issue so there shouldn't be any issues for players. They are mainly deleted light bulbs and clutter. Nothing that is being referenced by anything else so there isn't going to be any issue with them not being there as long as the users install the mod properly and clean the scripts from their saves as I've instructed.

As I stated earlier, adding this to LOOT will be a waste of time because...
1. The mod is going to be incorporated into the original Jaggarsfeld mod and the mod page deleted when that happens. "Jaggarsfeld Extended.esp" will likely cease to exist at that time.
2. I've already updated a cleaned version this morning.

I do appreciate the report, but I wish it was reported on my mod page so that I could handle it there and not have anyone on this team waste their time looking into the matter. LOOT handles the rest just fine by sorting it below its masters.

Thanks. This report can be closed.

**Comment by Freso** [comment]
> As I stated earlier, adding this to LOOT will be a waste of time because...

It is still worth getting added to LOOT as some people will have the old, non-cleaned versions of your mod lying around for an unknown amount of time.

> Nothing that is being referenced by anything else

You don't know. Unless you've checked every other mod in existence, past and future. If another mod references the record and your mod has deleted it, the game will crash.

**Comment by Freso** [comment]
Thanks @inire!

**Comment by Freso** [comment]
> I wish it was reported on my mod page so that I could handle it there

I do believe it should be reported upstream as well as here. How did you come to know about this report here though?

**Comment by inire** [comment]
@Freso you are welcome. I also didn't know how to add to the masterlist.yaml until after I posted this, or I would have made a pull request.

@TechAngel85 I noticed after cleaning that all the deletes were within the original mod package, but the authors between the two mods were different (i.e. your name on the extended and a bunch of different authors including your name on the original file). I meant no offense and would be happy to update the posts on the extended file nexus if you wish.

I am guessing that you built a google alert on the URI for your file or something similar.

**Comment by TechAngel85** [comment]
@Freso 
As long as users know it's for the old version that is fine. I don't remember if LOOT distinguishes between versions. If so it would be for version 2.3.x minus the latest version 2.3.3.

Also, everything in the Jaggarsfeld mod is in it's own worldspace and has no interaction with the outside world besides a map marker and a cave entrance. Jaggarsfeld Extended is the only mod which alters anything in that worldspace which as been uploaded to any modding site. I know this because no one can do anything without permission and JE is the only mod with those permissions. So if a mod does exist it is without permission from us and their mod deserves to break. Haha!

Someone alerted me to this report since it wasn't reported to me directly so that I may fix it. But it's fixed all good now.

@inire 
All is good. :) JE only alters content from Jaggarsfeld so that is what you would expect to see. I'm the author of JE and the co-author of Jaggarsfeld now. Darth and Jack have retired from the mod so I currently have control of both mods and in the process of a major update for Jaggarsfeld...which is why JE hasn't seen any attention, but I still fix reported bugs if I can.

**Comment by Freso** [comment]
> As long as users know it's for the old version that is fine.

The `crc` bit uniquely identifies exactly that one version of the .esp file. As soon as it has been cleaned or otherwise changed (e.g., if it's been updated to a newer version), the message will no longer be shown: https://en.wikipedia.org/wiki/Cyclic_redundancy_check

> So if a mod does exist it is without permission from us and their mod deserves to break.

Some users make changes to the game, including mods they have downloaded, without redistributing them. This is well within their rights (as long as they do not redistribute their modified works).

**Comment by TechAngel85** [comment]
Fair enough! ^_^

Good to know about the crc bit as well. I didn't know that. Learn something new every day! Back to dialoguing... >_<

**Comment by Freso** [comment]
Happy dialoguing. ;)
