### ISSUE TITLE
LOOT v0.9.2 (Load Order won't change after installing 4 mods)

### ISSUE THREAD

**Issue by DasCyan** [loot/skyrim#128]
Hi, so whenever I add new mods to Mod Organizer, I usually run LOOT to let it put the new mod in its place in my load order. I recently added AFT and noticed that LOOT has been making NO changes to my load order for the past 3-4 mods that I also recently installed, they all just stayed at the bottom like new .esps would be.

I tried jumbling up my load order by hand so that LOOT would be forced to fix my load order to make it correct. But it still made NO changes even though my load order was completely wrong.

What can I do to fix this? is there a way to reset LOOT or my load order?

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). This might be an MO issue though, I don't provide support for using LOOT through MO because it's pretty much impossible for me to do anything about it. Can you try installing some mods manually into your Data folder and seeing if LOOT will sort them correctly then?

**Comment by DasCyan** [comment]
I fixed it by disabling all the mods on the left pane, re-enabling them, then running LOOT again.

Thanks for your time though!
