### ISSUE TITLE
Can't edit metadata

### ISSUE THREAD

**Issue by javishpr** [loot/skyrim#130]
Moving it from the Bethesda Softworks forum as request:

[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/612224/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/skyrim/files/612225/CEFDebugLog.txt)

I'm trying to edit the metadata on some of my plugins, but honestly I can't find how to apply the things I'm adding. 
 
When I run LOOT and go to a specific plugin I click on the 3 dots that are on the right side of the plugin bar. From there I select "edit metadata" and proceed to add what I want to add to that plugin. After that I hit the "save metadata" at the top right side of the editor (right next to the "X"), but nothing happens. The editor stays opened and all I can do is hit the cancel "X".  The sort plugins and update the master list and grayed out and whatever other thing I can actually click will give me a message saying that I haven't "apply" the changes I made. I can't find any "apply" buttong or anything of that sort and as I said the "Save Metadata" does nothing. Anyone can help me what I need to do? cause I'm clueless atm LOL. Thanks for the help!

**Comment by Ortham** [comment]
It doesn't look like there's anything useful in those logs... What metadata were you trying to save for what plugin?

Also, for future reference, application issues should be filed [here](https://github.com/loot/loot/issues), this issue tracker is for the masterlist.

**Comment by javishpr** [comment]
I'm installing the S.T.E.P. mods following their guide and there are like 4 mods that the guide says need some metadata edits on LOOT. So I'm just following that, not sure if I don't need to and my load order is already correct.

**Comment by Ortham** [comment]
Specifics, please, it's a lot easier to fix an issue if I can replicate it, but I need to know exactly what you did to do the same.

**Comment by javishpr** [comment]
I went to this page http://wiki.step-project.com/STEP:2.2.9.2 and followed each step and installed every mod there. Up to the part to make the batched patch where it tells me to make sure I add the metadata to 4 plugins before sorting them.

**Comment by Ortham** [comment]
OK, I'll try that. Can you see if the issue still occurs with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-21-g97c8802_dev.7z)?

**Comment by javishpr** [comment]
I just made a new profile in Mod Organizer and added just a few mods and ran LOOT, but I still have the same problem when I try to edit a plugin.

**Comment by Ortham** [comment]
Oh, hang on, STEP is telling you to set priority values of 970000 and 960000 - is that what you're doing when you can't save the metadata? That'll be because v0.10.0 changed things so that values have to be between +/- 127, so the STEP guide is out of date.

The inputs should have changed to have a red underline when you tried to save the invalid values. I thought they'd actually prevent you from entering invalid values in the first place, which is why there's no error message, but I was wrong about that, so I've added a message too. Try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-26-gda42713_improve-priority-validation-ui.7z) and see if there's any other reason you can't spot for being unable to save your metadata.

**Comment by javishpr** [comment]
I edited the other two plugins that were for "Load after" and it did work. So yeah, that was the problem. The STEP guide is not up to date on that. I'll check that build and see. Thanks a lot!!!
