### ISSUE TITLE
Skyrim Race Records Master

### ISSUE THREAD

**Issue by Darklocq** [loot/skyrim#476]
[Skyrim Race Records Master](https://www.nexusmods.com/skyrim/mods/97281) is not a mod, but a meta-mod, a tool for detecting and correcting RACE record conflicts. 

"Race Records Master.esp" and "Race Records Master - mine.esp" need to be super-duper-mega-ultra last in the load order (and the former before the latter).  The entire point of them is to analyze and if necessary repair what ALL other mods (including bashed/smashed patch) are doing to NPC races.

"Race Records Master.esp" is not loaded in-game but just in TES5Edit (or the CK, if one likes self-torture, I guess).  If fixes are required, then a copy of it named "Race Records Master - mine.esp" is used to effectuate them, and is loaded in-game as a final "do things my way, dammit" patch.

**Comment by pStyl3** [comment]
We could add a new group for these plugins that loads last. For example:
```yaml
  - name: &noneGameplayGroup None Gameplay
    after: [ *mapGroup ]
```
That plus `after` data for the Bashed and Smashed Patch should place it at the end.
Opinions?

**Comment by sibir-ine** [comment]
@Darklocq The groups for SLE are probably a bit messy & excessive since we've mostly switched to SSE at this point, but, as they stand, it should be fine to put _Race Records Master - mine.esp_ in _Post-Reproccer Patches_. It's not dead last, but it should be fine as I doubt any map or LOD plugins are going to be editing race records. _Race Records Master.esp_ can be placed there too, but I don't imagine it'd be necessary as it's only meant to be used after your load order is established. We could also add an error message warning users not to use _Race Records Master.esp_ in-game.

**Comment by sibir-ine** [comment]
@Darklocq I made the changes I talked about earlier. Feel free to reopen this issue or file another if you have any issues with it or further questions.

**Comment by Darklocq** [comment]
Thanks for working it in. :-)

**Comment by sibir-ine** [comment]
You're welcome! Sorry for the delay.
