### ISSUE TITLE
RBB after SMIM

### ISSUE THREAD

**Issue by alpha0010** [loot/skyrim#53]
From what I can tell, Realistic Boat Bobbing needs to be after SMIM.  (I believe this was working until the alphabetical patch?)

**Comment by egocarib** [comment]
I don't think this is required. The author has written that it is an install order issue, not a load order issue (because you need RBB meshes to be installed after SMIM to take precedence). He also has offered an explicit SMIM patch with the mod and there is no mention of load order requirements RE: SMIM in any of the documentation or forum.
